flat_dire_bonjour.Rmd:
  path: dev/flat_dire_bonjour.Rmd
  state: active
  R: R/dire_bonjour.R
  tests: tests/testthat/test-dire_bonjour.R
  vignettes: vignettes/dire-bonjour.Rmd
  inflate:
    flat_file: dev/flat_dire_bonjour.Rmd
    vignette_name: Dire bonjour
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
