---
title: "flat_dire_bonjour.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# dire_bonjour

```{r development-dire_bonjour}
# Prepare the code of your function here
library(glue)
prenom <- "Vincent"
glue("Bonjour {prenom} !")

```

```{r function-dire_bonjour}
#' dire_bonjour
#' 
#' @param prenom Character. The user first name
#' @return A string saying hello
#' @export
#' @import glue glue
#' @examples
dire_bonjour <- function(prenom = "toi") {
  if (isFALSE(nzchar(prenom))) {
    stop("Your string is empty")
  }
  if (!is.character(prenom)){
    stop("Please provide a string as prenom")
  }
  return(
    glue("Bonjour, ", prenom, " !")
  )
}
```

```{r examples-dire_bonjour}
dire_bonjour("Denis")
dire_bonjour()
```

```{r tests-dire_bonjour}
test_that("dire_bonjour works", {
  expect_true(inherits(dire_bonjour, "function"))
})

test_that("dire_bonjour return a string", {
  expect_type(
    object = dire_bonjour("Denis"),
    "character"
  )
})

test_that("dire_bonjour returns error", {
  expect_error(
    object = dire_bonjour(2)
  )
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_dire_bonjour.Rmd", vignette_name = "Dire bonjour")
```
