# WARNING - Generated by {fusen} from dev/flat_dire_bonjour.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("dire_bonjour works", {
  expect_true(inherits(dire_bonjour, "function"))
})

test_that("dire_bonjour return a string", {
  expect_type(
    object = dire_bonjour("Denis"),
    "character"
  )
})

test_that("dire_bonjour returns error", {
  expect_error(
    object = dire_bonjour(2)
  )
})
