# WARNING - Generated by {fusen} from dev/flat_dire_bonjour.Rmd: do not edit by hand # nolint: line_length_linter.

#' dire_bonjour
#' 
#' @param prenom Character. The user first name
#' @return A string saying hello
#' @export
#' @import glue glue
#' @examples
#' dire_bonjour("Denis")
#' dire_bonjour()
dire_bonjour <- function(prenom = "toi") {
  if (isFALSE(nzchar(prenom))) {
    stop("Your string is empty")
  }
  if (!is.character(prenom)){
    stop("Please provide a string as prenom")
  }
  return(
    glue("Bonjour, ", prenom, " !")
  )
}
